### ISSUE TITLE
conda package - javascript

### ISSUE THREAD

**Issue by guillaume-gricourt** [SynBioDex/SBOL-utilities#132]
Hi,
An another error was found  (#121) when the package is tested on bioconda (bioconda/bioconda-recipes#35151).
Tests calling the script `sbolgraph-standalone.js` throw the error:
`"/usr/bin/env: invalid option -- 'S'\nTry '/usr/bin/env --help' for more information.\n"`

The runner launched by Bioconda has Ubuntu 20.04.4 LTS and `coreutils` (8.30-3ubuntu2) installed ([details](https://github.com/actions/virtual-environments/blob/ubuntu20/20220614.0/images/linux/Ubuntu2004-Readme.md))
Theorically, the `env` command, part of `coreutils`, accepts the argument `-S/--split-string` from the version 8.30. But, in practice, this argument is not recognized.

So, can we simplify the header of the file  `sbolgraph-standalone.js` ?

**Comment by jakebeal** [comment]
I closed this because I believe that your pull request addressed it; if this isn't the case, please re-open.
