### ISSUE TITLE
translating from GenBank ontology terms to SO and vice versa

### ISSUE THREAD

**Issue by mohitdmak** [SynBioDex/SBOL-utilities#146]
* Currently, the new offline GenBank-SBOL3 converter being implemented in `sbol_utilities/sbol3_genbank_conversion.py` on the `feature/sbol3-genbank-conversion` branch, uses two data files `gb2so.csv` and `so2gb.csv` to translate between ontology terms for GenBank and SO.
* The conversions in those CSV files are taken up from [here](https://docs.google.com/spreadsheets/u/1/d/1X870i3NhO7xEhqhLXK4eravNd72x-O-xbrpmlT835nY).
* There also needs to be default terms for GenBank/SO while converting; should no row in the CSV match the term present in the file to be converted, there are a couple of issues regarding this:

1. The default SO Term, if no GenBank term in `gb2so.csv` matches the term present in any feature of the given GenBank file to convert, is mentioned in the spreadsheet to be `SO:0000110`. However, this clashes with the default used by the [online converter](https://github.com/SynBioDex/libSBOLj), which is `SO:0000001`. In this case, which default should be accepted for the new converter?
2. Also, correspondingly, no default GenBank term is specified in the spreadsheet

**Comment by jakebeal** [comment]
In conversation with @cjmyers today, figured out the resolution.
1. I was confused: I thought SO:0000001 was the parent of SO:0000110, but it's actually the other way around.
2. The default GenBank term is misc_feature
