### ISSUE TITLE
Store GenBank References's location information as SBOL3 properties

### ISSUE THREAD

**Issue by mohitdmak** [SynBioDex/SBOL-utilities#169]
Iterating along the progress made in the PR: https://github.com/SynBioDex/SBOL-utilities/pull/158, we should also store each References' `FeatureLocation` objects as SBOL3 properties. 

This is not straightforward, though; here is some explanation of the issue:

### Issue with References:
* There can be any number of references for a GenBank record, and each of them has multiple **TextFields** *(like Authors, Title, Journal, Consortium, Date, etc.)*. Apart from this, each Reference also has a **location** field, which is an array of **FeatureLocations**.
* Currently, I have stored all the **TextFields** into a `TextListProperty` for each of them; and assigned them to a reference one by one while converting an SBOL3 file to GenBank.
* This could *kind of* be done for the **location** field too *(by using `OwnedObjectListProperty` with a **type constraint** of `FeatureLocation`), but would be a very messy way to do it. Since, while parsing SBOL3 -> GenBank, we wouldn't know how many locations to store in each **Reference**, we would also need to store **indexes** of end locations of each **Reference** in an array property for this to work.
* To avoid this, I had tried to create a custom **Property**  *(see the block of commented lines below the `Component_GenBank_Extension` class)*, but faced issues as apparently I need to return only **RDF Terms** from the **Property Mixin Class**, but they support only **Literal** Values. So this attempt led nowhere, but I have kept the commented lines for you to see if we can make this method work in some way.

A workaround was discussed in the PR:

> On the question of references: can you make extensions of CustomIdentified for Reference and for ReferenceLocation? They are objects, and that will let you deal with them as objects.

**Comment by tcmitchell** [comment]
Closed by #174
