### ISSUE TITLE
Set up read-the-docs

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-utilities#33]

**Comment by noahsprent** [comment]
I've been working on this in a fork:

https://sbol-utilities-ns.readthedocs.io/en/latest/index.html

I've added what I think are the bare-minimum files for read-the-docs and sphinx for generating them. We just need a .readthedocs.yaml configuration file in the root of the repo and this points to a docs folder that contains the sphinx workings.

The only step after merging this will be to import the repo to read-the-docs, which maybe you might want to be the admin of @jakebeal ?

If I can be given access rights to the repo I can submit a pull request from my fork and assign this issue to myself.

**Comment by jakebeal** [comment]
That sounds like a good plan. I looked to see if we could just have the organization be the owner, but I guess readthedocs doesn't support that yet.

**Comment by jakebeal** [comment]
Looks like the build is running, but the documentation is empty: https://readthedocs.org/projects/sbol-utilities/

**Comment by noahsprent** [comment]
That is what I mean by a 'minimal' setup. We can now edit the files in `docs` to create the docs!

**Comment by jakebeal** [comment]
Excellent; I'm leaving this issue open until the minimal docstrings build is added there

**Comment by noahsprent** [comment]
Docs are now live with autoapi reference page here: https://sbol-utilities.readthedocs.io/en/latest/
