### ISSUE TITLE
Error using convert3to2

### ISSUE THREAD

**Issue by Gonza10V** [SynBioDex/SBOL-utilities#53]
When using convert3to2 got FileNotFoundError: [Errno 2] No such file or directory: ...lib/python3.7/site-packages/sbol_utilities/sbolgraph-standalone.js. Is this an error on the library or I need to install something?

![Screen Shot 2021-10-29 at 19 27 04](https://user-images.githubusercontent.com/35148159/139507893-75613a3e-d419-4ccd-999d-93fb1867bea8.png)

**Comment by jakebeal** [comment]
Looks like the file isn't making it into the egg for the pypi distribution for some reason... I will try to figure out why that is and get out a patch.

In the meantime, it will work if you install from source. Clone the repository, and then in its root directory run: 
`pip3 install .`

**Comment by jakebeal** [comment]
OK, version 1.0-alpha13 is pushed with the distribution problem fixed, and I have tested it to see that it does install and run correctly. Please let me know if it's fixed for you as well.

**Comment by Gonza10V** [comment]
I tried both options that you mention and cloning the repository and installing with `pip install -e .` . All of them retrieve the same error attached.

![Screen Shot 2021-10-29 at 22 17 47](https://user-images.githubusercontent.com/35148159/139515565-5984e7de-32be-4447-a426-afa9b6a0c98d.png)

**Comment by jakebeal** [comment]
Well, we are progressing forward at least: now it's finding the Javascript but something's going wrong when it tries to run it.

I see that you are running in a virtual environment. Are you able to run other Javascript processes in there?
What happens if you just run the a test conversion using the `sbol3to2` terminal command on a file in your user space from the command line?

**Comment by tcmitchell** [comment]
Is it possible that [node](https://nodejs.org/) is not installed? 

I get error code 127 from `sbolgraph-standalone.js` when node is not installed.

```
$ venv/lib/python3.8/site-packages/sbol_utilities/sbolgraph-standalone.js
env: node: No such file or directory
$ echo $?
127
```

**Comment by Gonza10V** [comment]
Thanks Tom for your suggestion. I installed node and tried the code again. I think I've advanced in the error cascade and now I got the following error:

![Screen Shot 2021-10-31 at 15 58 44](https://user-images.githubusercontent.com/35148159/139597672-43e4dd9b-16b4-4220-832d-d84760f1fbec.png)

**Comment by Gonza10V** [comment]
I review my SBOL3 document and it have some errors. I test with the document generated on the pySBOL3 circuit example (https://github.com/SynBioDex/pySBOL3/blob/main/examples/circuit.py). This example produce an SBOL3 document without error but once converted the SBOL2 document has 6 errors, is this expected?
![Screen Shot 2021-10-31 at 16 39 08](https://user-images.githubusercontent.com/35148159/139598881-acb3d4af-bf1f-4424-9e56-667f889e2743.png)

**Comment by Gonza10V** [comment]
After looking for ways inspect those errors I noticed that I used validate method in the same way in SBOL3 and SBOL2. So the 6 objects were nos errors but letter of `Valid.`. The function is working well thanks for your help!
![Screen Shot 2021-10-31 at 17 13 34](https://user-images.githubusercontent.com/35148159/139599782-495374e7-7141-4721-945f-e9fb0fee700e.png)
