### ISSUE TITLE
Problems with contained_components

### ISSUE THREAD

**Issue by Gonza10V** [SynBioDex/SBOL-utilities#58]
Hi I want to get all Components from a set of features inside another Component. For that I wanted to use contained_component function on components (https://github.com/SynBioDex/SBOL-utilities/blob/develop/sbol_utilities/component.py). But I just obtain the root Component. Is the function not working or am I using it properly?

![Screen Shot 2021-11-15 at 19 00 37](https://user-images.githubusercontent.com/35148159/141859941-8ae956c4-bdd0-4a8b-9f08-bba20eefe202.png)

**Comment by jakebeal** [comment]
`contained_component` will not return `Feature` objects, but should return the `Component` objects that are pointed to by the `instance_of` fields of the `SubComponent` features. Have those been set? Can you share the document you're working with?

**Comment by Gonza10V** [comment]
Hi, here is a notebook showing the problem, the function works well in a simple example but fails to retrieve the `Components` from the features inside the provided `Component`.

[contained_components problem.ipynb.zip](https://github.com/SynBioDex/SBOL-utilities/files/7548560/contained_components.problem.ipynb.zip)

**Comment by Gonza10V** [comment]
Right, there is no way to obtain a `Component` that as been defined in another `Document`. I will try to solve my problem by providing the target `Document` file from which to look for `Components`. Thanks @jakebeal  for your help, then there is no problem with `contained_components` function.

**Comment by jakebeal** [comment]
I agree with your assessment, but I'm going to reopen this and take it on to make a more principled choice about which of the three options is preferable to contained components that are not in the document.
