### ISSUE TITLE
Switch readthedocs to main

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-utilities#79]
Currently the readthedocs set up by @noahsprent in #78 is pointing to the develop branch. I believe that we actually want it pointing to the releases on the main branch instead. We can't do that effectively, however, until we make a release that includes the readthedocs materials added in #78, howver.

**Comment by noahsprent** [comment]
I think actually a good solution to this might be to have the 'latest' docs on rtd point to the `develop` branch, but have a 'stable' docs that points to the most recent release on main. We can set the default docs to be the 'stable' docs, but if people want to see the latest docs for the develop branch (and if we want to see them before we merge to main) then they can select that in the bottom left.

See instructions for doing that [here](https://docs.readthedocs.io/en/stable/tutorial/#versioning-documentation)

For now, we can point the default to 'latest/develop' until we have a release that incorporates the docs into main (which I suggest we don't do until we have some docs for people to see!).

**Comment by Gonza10V** [comment]
I agree with Noah. The best is to have a stable version pointing to `master` and a latest version pointing to `dev`. I can set up that but first I would like to have some help writing the docs, any volunteer?

**Comment by noahsprent** [comment]
Thanks @Gonza10V! If you know about read-the-docs could I add you as a reviewer of #84? I've just added the bits to create the autoapi reference but there are a few warnings. I think we probably only need that, along with some text on the homepage and a link to the docs in the repository here before that makes it enough to push to `main` for the time being?  @jakebeal Do they sound like acceptable criteria for a `main` release? 

I think it's probably the priority to focus on the docs for the distro repository right now, which I'm going to work on, but it would be a useful exercise for me to help write more pages for these docs after we've got that going so happy to help then.

**Comment by jakebeal** [comment]
@noahsprent We can make a release whenever we have a significant improvement ready to push out --- I'm fine with minor versions and patch versions. If you're OK with #84, go ahead and merge it.

**Comment by Gonza10V** [comment]
@noahsprent Looks like you managed this to complete the merge of #84. Count with me to help you setting rtd documentations, it is a skill that I also need to improve.

**Comment by jakebeal** [comment]
Looks like sticking with "latest" is fine for now, and once it's declared out of pre-release, we'll get a "stable" branch and tagged branches automatically.
